# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [14]:
print(np.__version__)
np.show_config()

1.17.3
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/akshaypansari/anaconda3/envs/pytorch/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/akshaypansari/anaconda3/envs/pytorch/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/akshaypansari/anaconda3/envs/pytorch/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/akshaypansari/anaconda3/envs/pytorch/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/akshaypansari/anaconda3/envs/pytorch/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/home/akshaypansari/anaconda3/envs/pytorch/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/home/akshaypansari/anaconda3/envs/pytorch/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include

#### 3. Create a null vector of size 10 (★☆☆)

In [20]:
var = np.zeros(10)
print(var)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [42]:
var = np.zeros(10)
print("%d bytes"% (var.size * var.itemsize))
# itemsize(var)
# answer(4)

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [49]:
np.info(np.add)
?np.add
answer(5)
%run python -c "import numpy; numpy.info(numpy.add)"

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [52]:
var = np.zeros(10)
var[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [62]:
# ?np.arange
var7 = np.arange(10,50)
# print(var7)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [74]:
var8 = var7
ans = var8[::-2]
print(ans)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [80]:
var9 = np.arange(9).reshape(3,3)#don't need to write reshape((3,3))
print(var9)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [93]:
const10 = np.array([1,2,0,0,4,0])
var10 = np.nonzero(const10)
print(var10)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [94]:
var11 = np.eye(3,3)
print(var11)
hint(11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
hint: np.eye


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [98]:
var12 = np.random.random((3,3,3))
print(var12)

[[[0.05493756 0.56582614 0.85017995]
  [0.77611889 0.58720193 0.13695653]
  [0.49318811 0.63607201 0.27787082]]

 [[0.48735779 0.93669047 0.45804544]
  [0.38242364 0.91362039 0.20817168]
  [0.89103531 0.7618061  0.92230217]]

 [[0.48515241 0.14537623 0.60594629]
  [0.16837161 0.22667552 0.78426411]
  [0.3420711  0.41186545 0.24708203]]]
Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [99]:
var13 = np.random.random((10,10))
max13 = np.max(var13)
min13 = np.min(var13)
print(min13, max13)


0.004145025389671098 0.9979064463849014


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [103]:
var14 = np.random.random(30)
mean14 = np.mean(var14)
mean14 = var14.mean() #both are fine
print(mean14)

AttributeError: 'list' object has no attribute 'mean'

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [114]:
var15 = np.zeros((10,4))
var15[:,0]=var15[:,-1]=var15[0,:]=var15[-1,:] = 1
print(var15)

var15 = np.ones((4,10))
var15[1:-1,1:-1]=0
var15

#both method are correct

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [126]:
var16 = np.random.random((10,5))
np.pad(array=var16,pad_width=((1,1),(1,1)),mode='constant',constant_values = (0,0)) ##Good one

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.4235848 , 0.06225289, 0.09333774, 0.74151235,
        0.43792061, 0.        ],
       [0.        , 0.78275863, 0.37747435, 0.20182282, 0.27671869,
        0.95279195, 0.        ],
       [0.        , 0.61273835, 0.23924424, 0.02477023, 0.23282342,
        0.84662477, 0.        ],
       [0.        , 0.28409391, 0.56593944, 0.26833183, 0.63267449,
        0.09531696, 0.        ],
       [0.        , 0.22919601, 0.11468699, 0.09547353, 0.75489907,
        0.38063271, 0.        ],
       [0.        , 0.54976869, 0.26106192, 0.1863954 , 0.1754721 ,
        0.64863104, 0.        ],
       [0.        , 0.24170511, 0.22119863, 0.56948656, 0.12325467,
        0.44685843, 0.        ],
       [0.        , 0.20099624, 0.91108115, 0.6769446 , 0.78831562,
        0.50967562, 0.        ],
       [0.        , 0.72220691, 0.20809276, 0.48771868, 0.09279296,
        0.6850955 , 0. 

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [137]:
0 * np.nan # nan
np.nan == np.nan #False
np.inf > np.nan #Flase
np.nan - np.nan #nan
np.nan in set([np.nan]) #True
0.3 == 3 * 0.1 #False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [143]:
np.diag(np.array([1,2,3,4]), -1)
np.diag(np.arange(4)+1, -1)
#both are correct

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [153]:
#This one difficult for me
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

var19 = np.zeros((8,8), dtype = np.int8)
var19[::2, ::2] = 1
var19[1::2, 1::2] = 1
var19
# good one re try both are correct with same logic 
#reference : https://stackoverflow.com/questions/25876640/subsampling-every-nth-entry-in-a-numpy-array/25876672

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [170]:
#Difficult for me
# var20 = np.arange(6*7*8).reshape((6,7,8))
# var20 #1, 5, 3
np.unravel_index(99, (6,7,8), 'F')
# answer(20)

(3, 2, 2)

In [176]:
var20 = np.arange(6*7*8).reshape((6,7,8))
var20

array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 15

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [181]:
# See Question 19
var21 = np.tile(np.array([0,1]),(8,4))


Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [199]:
var22 = np.random.random((5,5))
mu = np.mean(var22)
sigma = np.std(var22)
var22_n = (var22-mu)/sigma
print(var22_n)
# answer(22)
#Try for just or column later

[[ 0.437741    0.94840601 -1.19891503 -1.00884941  0.45131922]
 [-0.76196463  1.43661896 -0.66721612  1.641253   -0.98572201]
 [-1.47940496  0.11100899 -1.17906347 -0.56283371 -0.61659556]
 [ 0.83799359  1.3080979  -0.6794572  -0.91235547  1.15311176]
 [ 0.26031308  0.98168087  1.52654379  0.27459071 -1.31630132]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [211]:
# var23 = np.array([1.2.3], dtype = np.ubyte)
color = np.dtype([("r", np.ubyte,1),
                   ("g", np.ubyte,1),
                   ("b", np.ubyte,1),
                   ("a", np.ubyte,1)])
answer(23)

color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


/home/akshaypansari/anaconda3/envs/pytorch/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [227]:
a = np.random.random((5,3))
b = np.random.random((3,2))
print(np.matmul(a,b),"\n",a@b)
np.dot(a,b)
#all three are same

[[0.84839188 0.73159062]
 [0.84918718 0.85759825]
 [0.79859422 0.70413723]
 [1.0248091  1.07610326]
 [0.30903154 0.28478824]] 
 [[0.84839188 0.73159062]
 [0.84918718 0.85759825]
 [0.79859422 0.70413723]
 [1.0248091  1.07610326]
 [0.30903154 0.28478824]]


array([[0.84839188, 0.73159062],
       [0.84918718, 0.85759825],
       [0.79859422, 0.70413723],
       [1.0248091 , 1.07610326],
       [0.30903154, 0.28478824]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [256]:
var25 = np.arange(12)
temp3 = (var25>2) & (var25<9)
print(temp3)
var25[temp3]*=-1
print(var25)
answer(25)

[False False False  True  True  True  True  True  True False False False]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11]
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [260]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [269]:
#Difficult
Z = np.array([1,2,3])
print(Z**Z) 
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z6>Z)
answer(27)
#F, , F, T, T, F

[ 1  4 27]
[1 2 4]
[False False False]
[0.+1.j 0.+2.j 0.+3.j]
[1. 2. 3.]
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

## Difficult
print(np.array(0)/np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [287]:
#Redo
answer(29)
Z = np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)), Z))
#The values of x1 with the sign of x2. This is a scalar if both x1 and x2 are scalars.

# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
[ 1.13371059  7.30291089 -8.70531231  6.01234348  1.92053146 -2.56190803
 -3.48803885  3.94634845 -4.2836141  -9.31762743]
[  2.   8.  -9.   7.   2.  -3.  -4.   4.  -5. -10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [293]:
a1 = np.array([1,34,1,4,32])
a2 = np.array([1,34,4,4,3])
print(np.intersect1d(a1,a2))

[ 1  4 34]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [310]:
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [314]:
np.sqrt(-1) == np.emath.sqrt(-1)
#False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [328]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)
#https://www.w3resource.com/python-exercises/numpy/python-numpy-datetime-exercise-2.php
answer(33)
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

Yestraday:  2020-08-04
Today:  2020-08-05
Tomorrow:  2020-08-06
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [335]:
#Difficult
for i in range(31):
    print(np.datetime64('2016-07-01','D')+np.timedelta64(i,"D"), end=' ')
# dates = np.datetime64('2020-08-04','D')+np.timedelta64(1,"D")
# print(dates)
np.arange('2016-07', '2016-08', dtype = 'datetime64[D]')

2016-07-01 2016-07-02 2016-07-03 2016-07-04 2016-07-05 2016-07-06 2016-07-07 2016-07-08 2016-07-09 2016-07-10 2016-07-11 2016-07-12 2016-07-13 2016-07-14 2016-07-15 2016-07-16 2016-07-17 2016-07-18 2016-07-19 2016-07-20 2016-07-21 2016-07-22 2016-07-23 2016-07-24 2016-07-25 2016-07-26 2016-07-27 2016-07-28 2016-07-29 2016-07-30 2016-07-31 

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [358]:
#Difficult
A = np.array([4,2,3,2])
B = np.array([-3,-1,-2,-1])
C = (A+B)*(-A/2)
answer(35)
np.add(A,B, out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)




A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


TypeError: No loop matching the specified signature and casting was found for ufunc true_divide

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [379]:
var36 = np.random.uniform(0,10,10)
#Method1 step function round,, divide by number 1 (//), subtract the float part
#method1
print(var36)
print("copysign, ceil",np.copysign(np.ceil(var36*-1),var36))
#method2 divide 1
print("int division method",var36//1)
#subtract float part
print("subtract remainder",var36-(var36%1))
#method4
(print("floor",np.floor(var36)))
#method 5 trunc
print("trunc", np.trunc(var36))
#astype
print("astype", var36.astype(int))
# answer(36)




[8.3591642  4.57228065 3.26460179 7.7814881  7.51368171 9.27249623
 4.69641378 7.90589365 3.20998998 0.34952937]
copysign, ceil [8. 4. 3. 7. 7. 9. 4. 7. 3. 0.]
int division method [8. 4. 3. 7. 7. 9. 4. 7. 3. 0.]
subtract remainder [8. 4. 3. 7. 7. 9. 4. 7. 3. 0.]
floor [8. 4. 3. 7. 7. 9. 4. 7. 3. 0.]
trunc [8. 4. 3. 7. 7. 9. 4. 7. 3. 0.]
astype [8 4 3 7 7 9 4 7 3 0]


#### 37. Create a 5x5 matrix with column values and row values ranging from 0 to 4 (★★☆)

In [394]:
print(np.tile([[0],[1],[2],[3],[4]],5))
print(np.tile([0,1,2,3,4],5).reshape((5,5)))
answer(37)
Z = np.zeros((5,5))
Z+=np.arange(5)
(print(Z))

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [406]:
def genfunc():
    for x in range(10):
        yield x

var38 = np.fromiter(genfunc(), dtype=float, count=-1)
iterable = (x*x for x in range(5))
ans = np.fromiter(iterable, int)
print(ans)
print(var38)
# answer(38)

[ 0  1  4  9 16]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [327]:
np.linspace(start=0, stop = 1, endpoint=False, num=11)[1:]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [411]:
var40 = np.random.random(10)
print(var40)
np.sort(var40)

[0.15652829 0.68533368 0.70646847 0.18540483 0.07517921 0.08921435
 0.56361928 0.00316471 0.13224996 0.1275809 ]


array([0.00316471, 0.07517921, 0.08921435, 0.1275809 , 0.13224996,
       0.15652829, 0.18540483, 0.56361928, 0.68533368, 0.70646847])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [413]:
var41 = np.array([1,2,3,4,5])
print(np.add.reduce(var41))

15


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [456]:
a = np.ones(4)
b = np.ones(4)
#method 1 ==
a==b
#method 2
np.array_equal(a,b)
#method3  if within certain tolerance
np.allclose(a,b)
# answer(42)

[1 1 0 1 0] [1 1 0 0 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [462]:
var43 = np.zeros(10)
var43[0] = 1
print("Now making immutable")
# var43.flags.writeable = False
var43[1] = 1
print(var43)
answer(43)

Now making immutable
[1. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [479]:
cc = np.random.randint(100 ,size = (10,2))
x,y = cc[:,0], cc[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r,t)


[ 65.36818798  47.01063709 109.          61.7170965   63.03173804
   6.70820393  71.02112362  61.3514466   91.41662868  27.65863337] [1.0592402  1.05956561 0.58291359 0.86568498 0.72927738 1.10714872
 1.00622693 1.23873686 0.52728705 0.21866895]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [511]:
var45 = np.random.random(10)
print(var45)
var45[(max(var45)==var45)]=-1
var45[var45.argmax()]=-1
print(var45)
# np.where(max(var45))
answer(45)

[0.15298216 0.01521809 0.7144544  0.04967831 0.51829825 0.17902224
 0.66003662 0.24129003 0.88108253 0.31691434]
[ 0.15298216  0.01521809 -1.          0.04967831  0.51829825  0.17902224
  0.66003662  0.24129003 -1.          0.31691434]
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [506]:
#difficult and good one REDO


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [508]:
#difficult
X = np.array([1,2,3,4])
Y = np.array([-3,4])
print(1/np.subtract.outer(X,Y))
# C = np.zeros((X.shape[0], Y.shape[0]))
# def func(X,Y):
#     yield 1/(X[i]-Y[j])
    
# for i in range()


[[ 0.25       -0.33333333]
 [ 0.2        -0.5       ]
 [ 0.16666667 -1.        ]
 [ 0.14285714         inf]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [519]:
#difficult
# answer(48)
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)
    
    

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [526]:
# ?np.set_printoptions4
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)
#difficult
# answer(49)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [557]:
a = np.random.uniform(10,100)
vec = np.random.random(100)*100
# print(a,vec)
# print(np.abs(vec-a).argmin())
print(a, vec[np.abs(vec-a).argmin()])
# import numpy as np
# x = np.arange(100)
# print("Original array:")
# print(x)
# a = np.random.uniform(0,100)
# print("Value to compare:")
# print(a)
# index = (np.abs(x-a)).argmin()
# print(index)
# print(x[index])

61.39523850571591 61.95997234498538



#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [569]:
answer(51)
arr = np.zeros(10,[ ('position', [('x',np.float16),
                          ('y',np.float16),
                            ('r',np.int8)]),
               ('color',    [('g',np.int8),
                           ('b',np.int8)])])
print(arr)


Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)
[((0., 0., 0), (0, 0)) ((0., 0., 0), (0, 0)) ((0., 0., 0), (0, 0))
 ((0., 0., 0), (0, 0)) ((0., 0., 0), (0, 0)) ((0., 0., 0), (0, 0))
 ((0., 0., 0), (0, 0)) ((0., 0., 0), (0, 0)) ((0., 0., 0), (0, 0))
 ((0., 0., 0), (0, 0))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [587]:
#To complete
x = np.arange(9)
np.atleast_3d(x)

0

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [609]:
f = np.array([1.33,1.343,89.9], dtype = np.float16)
k = f.view(dtype = np.int16)
k[:]=f
print(k)
answer(53)
Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[ 1  1 89]
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)
[78.05921  20.928188 88.59386  65.54351  92.65029   3.193544 24.277504
 31.987637 30.950388 39.402676]
[78 20 88 65 92  3 24 31 30 39]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [620]:
# 
from io import StringIO
#FakeFILE
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
                ''')
np.genfromtxt(s, delimiter=',',filling_values=0.9)

array([[ 1. ,  2. ,  3. ,  4. ,  5. ],
       [ 6. ,  0.9,  0.9,  7. ,  8. ],
       [ 0.9,  0.9,  9. , 10. , 11. ]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [634]:
arr = np.arange(6).reshape((2,3,1))
for index, x in np.ndenumerate(arr):
    print(index,x)
for index in np.ndindex((2,3,1)):
    print(index,arr[index])
answer(55)

(0, 0, 0) 0
(0, 1, 0) 1
(0, 2, 0) 2
(1, 0, 0) 3
(1, 1, 0) 4
(1, 2, 0) 5
(0, 0, 0) 0
(0, 1, 0) 1
(0, 2, 0) 2
(1, 0, 0) 3
(1, 1, 0) 4
(1, 2, 0) 5
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

hint: np.meshgrid, np.exp


#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [647]:
arr = np.arange(12).reshape((6,2)) #np.random.rand(5,10)
mean = (arr.mean(axis=1)).reshape(-1,1) #arr - arr.mean(axis = 1, keepdims = True)
# mean = np.expand_dims(mean,(6,1))/
print(arr-mean)
# answer(58)

[[-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]
 [-0.5  0.5]]


#### 59. How to sort an array by the nth column? (★★☆)

In [660]:
#Difficult and good, can't use function as it is not sorted
arr = np.random.rand(10,5)
# arr.sort(key = lambda x : x[2] )
# answer(59)

Z = np.random.randint(0,10,(4,3))
print(Z)
print(Z[Z[:,2].argsort()])

[[8 4 9]
 [5 9 3]
 [2 7 7]
 [5 0 4]]
[[5 9 3]
 [5 0 4]
 [2 7 7]
 [8 4 9]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

hint: any, ~


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)